# Generated by Django 3.0.3 on 2020-06-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workedhours',
            options={'managed': True},
        ),
    ]
