# Generated by Django 3.0.3 on 2020-06-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20200618_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.AuthUser'),
        ),
        migrations.AddField(
            model_name='company',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.AuthUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.AuthUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.Company'),
        ),
        migrations.AddField(
            model_name='workedhours',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.Category'),
        ),
        migrations.AddField(
            model_name='workedhours',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.Project'),
        ),
    ]
