# Generated by Django 3.0.3 on 2020-06-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20200618_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='workedhours',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registro.AuthUser'),
        ),
    ]
